spring.datasource.url=jdbc:mysql://localhost:3306/tangerine_Digital_Task
spring.datasource.username=root
spring.datasource.password=navisna@23
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true